kind = "web"
previewPath = "/"
title = "Certfolio"
version = "1.0.0"
id = "artifacts/certfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23107

[services.development]
run = "pnpm --filter @workspace/certfolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/certfolio", "run", "build" ]
publicDir = "artifacts/certfolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23107"
BASE_PATH = "/"
